### ISSUE TITLE
Support Concat String using + Operator

### ISSUE THREAD

**Issue by hantsy** [jakartaee/expression-language#246]
Currently + is only used for numbers. 

Support `+` in String/literal texts concatenation.

Assume `a`, `b` are numbers, `c` is a string.

1. `c+a+b` for concat strings
2. `a+b` is for number adding operations.
3. `''+a+b` is for concat strings.

**Comment by markt-asf** [comment]
This was discussed back in 2013 as part of JSR 341. '+' was proposed but rejected due to backwards compatibility concerns since '+' is the addition operator. I don't have access to the discussion that concluded there was a backwards compatibility issue since that was an internal Oracle discussion where only the conclusion was reported back to the list.

Looking at the specification I think I can see what the problem is.

Evaluating `${'1' + 1} currently coerces the first argument to a Long and then addition is performed with the result of a Long with the value 2. This proposal would change the output to the String '11'.

Breaking backwards compatibility is something we try very, very hard to avoid  so I don't think this proposal can be implemented.

**Comment by OndroMih** [comment]
There's already the `+=` operator for concatenating strings. And it was probably invented for the reasons that @markt-asf described - to avoid incompatible changes.

**Comment by hantsy** [comment]
Why do we stick to keeping compatibility if most developers accept using `+` to concat strings?

**Comment by hantsy** [comment]
> There's already the `+=` operator for concatenating strings.

This is very strange for developers, `+=` can concatenate strings, but `+` can NOT.

**Comment by markt-asf** [comment]
As per my comment a few days ago, this can't be implemented without breaking backwards compatibility and we aren't going to do that.
